Scalar mul for MatZ
qfall/math pull request #157
Opened 2023-04-05 11:46 UTC by Marcel583

Implements scalar multiplication for MatZ.

2023-04-05 14:03 UTC, jnsiemer requested changes
Good work, please consider my comments below to use scalar multiplication more natively, keep the code to maintain as small as possible, and keep the doc comments consistent/correct.

2023-04-05 19:58 UTC, Marcel583 commented on src/integer/mat_z/arithmetic/mul_scalar.rs
> +use crate::traits::*;
They are imported in compile time, not run time, therefore it is not more efficient to import them separately.
Furthermore, if we change the traits, we do not need to refactor later (safes time in implementation).

2023-04-05 20:33 UTC, jnsiemer commented on src/integer/mat_z/arithmetic/mul_scalar.rs
> +use crate::traits::*;
Compile time sounds just a little bit less aweful than runtime as all doc tests are compiled on their own. Hence, I would love to also optimize compile time (if it's as easy as it is here). It's aweful enough that we do `use qfall_math::traits::*;` for these functions implementing our traits, but this way, we will import them all for all doc tests that we have (if this isn't optimized in another way, but then please show me a source that it doesn't impact compile time of doc tests that do not themselves explicitely import these traits).

2023-04-05 20:40 UTC, Marcel583 commented on src/integer/mat_z/arithmetic/mul_scalar.rs
> +impl Mul<&Z> for &MatZ {
It is not possible simply with Into<Z>, but I have added a macro for that.

2023-04-05 20:44 UTC, Marcel583 commented on src/integer/mat_z/arithmetic/mul_scalar.rs
> +use crate::traits::*;
Ok

2023-04-06 13:35 UTC, jnsiemer approved these changes

2023-04-06 16:08 UTC, merged