get_vec for MatZ
qfall/math pull request #161
Opened 2023-04-07 13:29 UTC by Marcel583

Implements  get_vec for MatZ.

2023-04-07 15:08 UTC, jnsiemer requested changes
Good work, I have some suggestions which would make the functions more efficient, the tests more meaningful, and the doc comments according to our specification.

2023-04-07 15:08 UTC, jnsiemer commented on src/integer/mat_z/get.rs
> +        let row = matrix.get_vec_row(1).unwrap();
```suggestion
        let matrix = MatZ::from_str(&format!("[[0,0,0][1,2,3],[4,{},{}]]", i64::MAX, i64::MIN)).unwrap();
        let row_0 = matrix.get_row(0).unwrap();
        let row_1 = matrix.get_row(1).unwrap();
        let row_2 = matrix.get_row(2).unwrap();
```
Please test all rows that you initialized and also include a zero row/column to the tests and compare it appropriately. I shortly took a look whether a check if the row/column is zero is worth it, but I believe that the check takes up almost as much time as fetching and setting the entire row (and getting a zero vector should hopefully not be done too often).

2023-04-08 10:43 UTC, Marcel583 commented on src/integer/mat_z/get.rs
> +                .unwrap();
I also need to implement evaluate indices manually for one index too

2023-04-08 11:58 UTC, jnsiemer approved these changes
Great work!

2023-04-09 08:10 UTC, merged