Refactor_sprint5
qfall/math pull request #196
Opened 2023-04-18 19:53 UTC by 3pmile

2023-04-19 10:53 UTC, Marvin-Beckmann requested changes
Loooks good, just two other comments:

- doc comment for power trait has to be fixed
- cargo doc still has a warning: `warning: unused manifest key: bench.0.autodiscovery` can you find out why (potentially ask @MoogSven if he knows)

2023-04-19 10:53 UTC, Marvin-Beckmann commented on src/integer/mat_z/arithmetic/add.rs
> +        assert_eq!(
There are still some assert!( * == *) in arithmetics for PolyOverZ.

2023-04-19 19:07 UTC, 3pmile commented
@MoogSven why do we need autodiscovery = false in benches? 
It was unused and i removed it for now

2023-04-20 09:21 UTC, MoogSven commented
Seems to also work without `autodiscovery`, therefore it can be removed.

2023-04-20 09:42 UTC, Marvin-Beckmann approved these changes

2023-04-20 09:47 UTC, merged