Numtraits for rational
qfall/math pull request #271
Opened 2023-05-15 10:51 UTC by 3pmile

**Description**

This PR implements...
- [ ] is_zero for Q, MatQ, PolyOverQ
- [ ] is_one for Q, PolyOverQ
- [ ] is_square and is_identity for MatQ

for/ of `Component`.

**Testing**

- [ ] I added basic working examples (possibly in doc-comment)
- [ ] I added tests for large (pointer representation) values
- [ ] I triggered all possible errors in my test in every possible way
- [ ] I included tests for all reasonable edge cases

**Checklist:**

- [ ] I have performed a self-review of my own code
  - [ ] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [ ] The chosen implementation is not more complex than it has to be
  - [ ] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [ ] The doc comments fit our style guide
  - [ ] I have credited related sources if needed

2023-05-23 17:02 UTC, MoogSven requested changes
Did not finish the review, since many of the suggestions are already part of #270.
Please check which of the suggestions from that pull request also apply to this one.

So far:
- [x] remove brackets at assert!(!([...])).
- [x] avoid unnecessarily complicated numbers
- [ ] Maybe use MatQ::new([...]) or similar functions instead of from_str if the values are not important.
- [ ] How to handle non square matrices

2023-05-23 17:02 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +
```suggestion
```

2023-05-24 09:21 UTC, 3pmile commented on src/rational/mat_q/properties.rs
> +        let large = MatQ::from_str(&format!("[[1, 0],[0, {}]]", (u128::MAX - 1) / 2 + 2)).unwrap();
this is 2^127 which is 0 in the for the last 64 bit

2023-05-24 09:31 UTC, 3pmile commented on src/rational/mat_q/properties.rs
> +        let large = MatQ::from_str(&format!("[[0, 0],[{}, 0]]", (u128::MAX - 1) / 2 + 1)).unwrap();
same reason as above, the last bits are all 0

2023-05-25 08:55 UTC, 3pmile commented on src/rational/mat_q/properties.rs
> +        self.is_square() && 1 == unsafe { fmpq_mat_is_one(&self.matrix) }
This implementation is equal to other is_identity implementations

2023-06-07 09:23 UTC, closed without merging