Set for MatPolyRingZq
qfall/math pull request #282
Opened 2023-05-18 08:35 UTC by Marcel583

**Description**

This PR implements Set for MatPolyRingZq.

**Testing**

- [ ] I added basic working examples (possibly in doc-comment)
- [ ] I added tests for large (pointer representation) values
- [ ] I triggered all possible errors in my test in every possible way
- [ ] I included tests for all reasonable edge cases

**Checklist:**

- [ ] I have performed a self-review of my own code
  - [ ] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [ ] The chosen implementation is not more complex than it has to be
  - [ ] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [ ] The doc comments fit our style guide
  - [ ] I have credited related sources if needed

2023-05-19 12:05 UTC, jnsiemer commented on src/integer_mod_q/mat_polynomial_ring_zq/set.rs
> +    /// # Examples
Missing `Returns ...`

2023-05-19 12:05 UTC, jnsiemer commented on src/integer_mod_q/mat_polynomial_ring_zq/set.rs
> +    /// # Examples
Missing `Returns ...`

2023-05-25 09:05 UTC, jnsiemer requested changes

2023-05-26 10:25 UTC, Marcel583 commented on src/integer_mod_q/mat_polynomial_ring_zq/set.rs
> +    const BITPRIME64: u64 = 18446744073709551557;
I think that is something for a refactor. This constant is everywhere, I only adapted it from Marvin.

2023-06-08 19:01 UTC, jnsiemer approved these changes

2023-06-10 08:57 UTC, merged