Q_Numtraits
qfall/math pull request #307
Opened 2023-06-07 09:02 UTC by 3pmile

**Description**

This PR implements...
- [x] is_zero for Q, MatQ, PolyOverQ
- [x] is_one for Q, PolyOverQ
- [x] is_square and is_identity for MatQ

as a new https://github.com/qfall/math/pull/271 .

**Testing**

- [x] I added basic working examples (possibly in doc-comment)
- [x] I added tests for large (pointer representation) values
- [x] I triggered all possible errors in my test in every possible way
- [x] I included tests for all reasonable edge cases

**Checklist:**

- [x] I have performed a self-review of my own code
  - [x] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [x] The chosen implementation is not more complex than it has to be
  - [x] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [x] The doc comments fit our style guide
  - [x] I have credited related sources if needed

2023-06-12 12:48 UTC, MoogSven requested changes
Mostly comment changes:
- [x] Sentences should start with upper case and end with a dot. (Test case describtion, Returns [...]**.**)
- [x] Add `# Examples`

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +    /// `0`.
Explicitly mention that non quadratic matrices are allowed.

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +    ///
`# Examples` missing here and at the next two functions

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +    /// ensure that is_identity returns `true` for identity matrices
```suggestion
    /// Ensure that is_identity returns `true` for identity matrices.
```
Start with upper case and end with a dot as discussed today. Also applies to the next comments.

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +
Add a test for a non square identity.

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +        assert!(!large.is_square());
Variable names do not really fit here. Maybe call them `mat_2x3` and `mat_3x2` instead
```suggestion
        let mat_2x3 = MatQ::from_str("[[0, 5/6, 4],[2/7, 0, 1]]").unwrap();
        let mat_3x2 = MatQ::from_str("[[9, 0],[127/71, 0],[0, 0]]").unwrap();

        assert!(!mat_2x3.is_square());
        assert!(!mat_3x2.is_square());
```

2023-06-12 12:48 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +    /// Returns true if the first coefficient is `1` and is the only coefficient
```suggestion
    /// Returns true if the first coefficient is `1` and is the only coefficient.
```
Also for the other functions

2023-06-12 12:48 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +    ///
```suggestion
    ///
    /// # Examples
```

2023-06-12 12:48 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +    ///
Also for the other functions

2023-06-12 12:48 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +        assert!(!(large.is_one()));
```suggestion
        assert!(!small.is_one());
        assert!(!large.is_one());
```
should be the same

2023-06-12 12:48 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +        assert!(!(large.is_zero()));
```suggestion
        assert!(!small.is_zero());
        assert!(!large.is_zero());
```

2023-06-12 12:48 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +    /// ensure that is_identity returns `true` for identity matrices
Optionally also backticks around the function name.
```suggestion
    /// Ensure that `is_identity` returns `true` for identity matrices.
```

2023-06-14 12:59 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +
Added in doc test

2023-06-14 13:11 UTC, MoogSven approved these changes
Please check and fix the open conversation points before merging.

2023-06-14 13:11 UTC, MoogSven commented on src/rational/poly_over_q/properties.rs
> +        assert!(!(large.is_one()));
Why did you not add this suggestion?

2023-06-14 13:11 UTC, MoogSven commented on src/rational/q/properties.rs
> +        assert!(!(large.is_zero()));
```suggestion
        assert!(!small.is_zero());
        assert!(!large.is_zero());
```

2023-06-14 13:11 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +        assert!(mat_3x2.is_square());
```suggestion
        let mat_2x2 = MatQ::from_str("[[0, 4/9],[0, 0]]").unwrap();
        let mat_3x3 = MatQ::from_str("[[0, 6/123, 4/7],[0, 0, 1/213],[4/341, 6/83, 1]]").unwrap();

        assert!(mat_2x2.is_square());
        assert!(mat_3x3.is_square());
```

2023-06-14 13:23 UTC, MoogSven commented on src/rational/mat_q/properties.rs
> +    /// assert!(value.is_identity())
Add a semicolon at the end of your assert macros. This applies to all tests.

2023-06-14 23:32 UTC, 3pmile commented on src/rational/poly_over_q/properties.rs
> +        assert!(!(large.is_one()));
overlocked it

2023-06-15 00:04 UTC, merged