refactor sprint 8
qfall/math pull request #309
Opened 2023-06-09 14:22 UTC by Marcel583

**Description**

This PR refactors
- [x] replace from_str by from
- [x] Fix warnings in crate
- [x] spelleing: occurence -> occurrence
- [x] &*[a-z,A-Z].modulus.modulus -> [a-z,A-Z].modulus.get_fmpz_mod_ctx_struct()
- [x] warning for CMP of PolyOverZq
- [x] Modulus Error in set entry of MatZq in missing (maybe in other modules too)
- [x] same as in get module, description in set module must be changed
- [x] MatPolyOverZ does not use macros (for example: set)
- [x] close TODO in new of matrices (use indices not index)
- [x] Add `Return ...` for functions returning `Result<(), MathError>`

**Testing**

- [ ] I added basic working examples (possibly in doc-comment)
- [ ] I added tests for large (pointer representation) values
- [ ] I triggered all possible errors in my test in every possible way
- [ ] I included tests for all reasonable edge cases

**Checklist:**

- [ ] I have performed a self-review of my own code
  - [ ] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [ ] The chosen implementation is not more complex than it has to be
  - [ ] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [ ] The doc comments fit our style guide
  - [ ] I have credited related sources if needed

2023-06-11 20:30 UTC, 3pmile requested changes

2023-06-11 20:30 UTC, 3pmile commented on src/utils/index.rs
> +
is this still in for a reason? if yes, why no tests

2023-06-12 14:00 UTC, 3pmile commented on src/utils/index.rs
> +    let column_i64 = evaluate_index(index2)?;
naming?

2023-06-13 11:29 UTC, Marcel583 commented on src/integer/mat_z/sample/uniform.rs
> +        let modulus = Modulus::try_from_z(&Z::from(7)).unwrap();
Yes, that`s why I wrote it in the next refactoring

2023-06-13 11:47 UTC, Marcel583 commented on src/integer/z/cmp.rs
>          assert!(small_1 == small_1);
Why? They are equal, but clippy wants us not to use unnecessary brackets.

2023-06-13 11:47 UTC, Marcel583 commented on src/rational/q/cmp.rs
> -        assert!(!(max == small_positive));
s.o.

2023-06-14 09:07 UTC, 3pmile commented on src/integer/z/cmp.rs
>          assert!(small_1 == small_1);
Then please move the tests to the right test case or remove them entirely

2023-06-14 23:46 UTC, 3pmile commented on src/integer/z/cmp.rs
>          assert!(small_1 == small_1);
Equal tests are now in the not_equal_... test case and the other way around

2023-06-15 10:47 UTC, 3pmile approved these changes

2023-06-15 10:47 UTC, merged