Implement new_cyclic and new_anticyclic ModPolyRingZq
qfall/math pull request #377
Opened 2023-08-22 14:23 UTC by jnsiemer

**Description**
This PR implements...
- [x] new_cyclic
- [x] new_anticyclic

for/ of `ModulusPolynomialRingZq`.

**Testing**
- [x] I added basic working examples (possibly in doc-comment)
- [x] I triggered all possible errors in my test in every possible way
- [x] I included tests for all reasonable edge cases

**Checklist:**
- [x] I have performed a self-review of my own code
  - [x] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [x] The chosen implementation is not more complex than it has to be
  - [x] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [x] The doc comments fit our style guide

2023-08-22 14:50 UTC, Marvin-Beckmann requested changes
The functionality on its own is a nice to have, but I do not think, that it should be in the math crate.
e.g. I also included the rotation matrices in the crypto crate.
I personally prefer them to be in the crypto crate, specifically if we are explicitly talking about default lattices here.

2023-08-22 14:50 UTC, Marvin-Beckmann commented on src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
> +    }
This modulus only indirectly defines an anti-cyclic lattice (i.e. using the coefficeint embedding) otherwise this only defines an anti-cyclic ideal.

2023-08-22 14:50 UTC, Marvin-Beckmann commented on src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
> +
see above

2023-08-22 14:50 UTC, Marvin-Beckmann commented on src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
> +#[cfg(test)]
please also compare the entries of the polynomial, such that the first coefficient is 1/-1 and the last is 1

2023-09-05 07:25 UTC, jnsiemer commented
Contents were moved to `utils::common_moduli` module in crypto-crate. See https://github.com/qfall/crypto/pull/43

2023-09-05 07:25 UTC, closed without merging