MatPolyRingZq scalar multiplication
qfall/math pull request #387
Opened 2023-08-28 14:03 UTC by Marcel583

**Description**

This PR implements scalar multiplication for MatPolyRingZq.

**Testing**

- [ ] I added basic working examples (possibly in doc-comment)
- [ ] I added tests for large (pointer representation) values
- [ ] I triggered all possible errors in my test in every possible way
- [ ] I included tests for all reasonable edge cases

**Checklist:**

- [ ] I have performed a self-review of my own code
  - [ ] The code provides good readability and maintainability s.t. it fulfills best practices like talking code, modularity, ...
    - [ ] The chosen implementation is not more complex than it has to be
  - [ ] My code should work as intended and no side effects occur (e.g. memory leaks)
  - [ ] The doc comments fit our style guide
  - [ ] I have credited related sources if needed

2023-09-05 08:04 UTC, jnsiemer requested changes

2023-09-05 08:04 UTC, jnsiemer commented on src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
> +        assert_eq!(cmp_poly_ring_mat, poly_ring_mat2);
Please also include the polynomial reduction in this case. For that you need to use a multiplication with a polynomial that has degree at least 1 s.t. the degree of the initial PolyRingZq get's larger by multiplication. But in this case, you would need a polynomial like `3  1 0 2` to make the modulus as a polynomial being applied in the matrix.

2023-09-05 08:04 UTC, jnsiemer commented on src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
> +impl Mul<&PolynomialRingZq> for &MatPolynomialRingZq {
Probably implement the PolyOverZ version, then use that one for the PolynomialRingZq and PolyOverZq implementations. Then, you just need to test whether the PolyOverZq and PolynomialRingZq implementations fail for different moduli and everything else is already tested via the PolyOverZ implementation.

2023-09-06 14:11 UTC, Marcel583 commented on src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
> +    fn mul(self, scalar: &PolynomialRingZq) -> Self::Output {
I also added mul_safe for these multiplications to be consistent with other scalar multiplications

2023-09-06 20:50 UTC, jnsiemer approved these changes

2023-09-07 09:19 UTC, merged